### ISSUE TITLE
Error: Unrecognized option 'enableSourcemap'

### ISSUE THREAD

**Issue by RockyKev** [c-bandy/website#152]
Hi!
Really like your build and blog post.

I pulled down your repo, and built it locally. I hit this error when I `npm run dev`

## ISSUE
```
Error: Unrecognized option 'enableSourcemap'
    at file:///G:/Development/frontend-masters-sveltekit/node_modules/svelte/compiler.mjs:31265:19
    at Array.forEach (<anonymous>)
    at validate_options (file:///G:/Development/frontend-masters-sveltekit/node_modules/svelte/compiler.mjs:31259:26)
    at compile (file:///G:/Development/frontend-masters-sveltekit/node_modules/svelte/compiler.mjs:31303:5)
    at compileSvelte2 (file:///G:/Development/frontend-masters-sveltekit/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:313:20)
    at async TransformContext.transform (file:///G:/Development/frontend-masters-sveltekit/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1460:27)
    at async Object.transform (G:\Development\frontend-masters-sveltekit\node_modules\vite\dist\node\chunks\dep-92cbd8f1.js:42412:30)
    at async doTransform (G:\Development\frontend-masters-sveltekit\node_modules\vite\dist\node\chunks\dep-92cbd8f1.js:56776:29)
```

## SOLUTION
https://githubmemory.com/repo/sveltejs/kit/issues/2646

Pretty straightforward. Upgrade Svelte.

https://github.com/RockyKev/frontend-masters-sveltekit/commit/8a3f55bb2520aeee7e139c5f0feaaeb04cebe7bd

**Comment by c-bandy** [comment]
Fixed!
